name: Benchmarks

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  benchmarks:
    permissions:
      contents: write # we'll push to the `benchmarks` branch
    name: Benchmarks
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: regal
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: regal/go.mod
          cache-dependency-path: regal/go.sum
      - name: gobenchdata publish
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_GO_TEST_FLAGS: "-timeout=120m -run=^#"
          INPUT_GO_TEST_PKGS: ./...
          INPUT_SUBDIRECTORY: regal
          INPUT_PUBLISH: true
          INPUT_PUBLISH_BRANCH: benchmarks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 120
