name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  build-matrix:
    env:
      RQ_VERSION: v0.0.15
    name: Matrix
    strategy:
      matrix:
        os:
          - runner: ubuntu-latest
            name: linux
            static: true
          - runner: macos-15-intel
            name: macos-intel
            static: false
          - runner: macos-26
            name: macos-arm64
            static: true
          - runner: windows-latest
            name: windows
            static: true
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - uses: open-policy-agent/setup-opa@950f159a49aa91f9323f36f1de81c7f6b5de9576 # v2.3.0
        with:
          version: latest
          static: ${{ matrix.os.static }}
      - run: npm ci
        working-directory: build
      - name: Restore rq cache
        id: cache-rq
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: go install git.sr.ht/~charles/rq/cmd/rq@${{ env.RQ_VERSION }}
        if: steps.cache-rq.outputs.cache-hit != 'true'
      - name: Cache rq binary
        if: steps.cache-rq.outputs.cache-hit != 'true'
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: build/do.rq pull_request
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        if: matrix.os.name == 'linux'
        with:
          version: v2.6.2
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: regal-${{ matrix.os.name }}
          path: regal

  race_detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - run: go test -race ./...
        id: race
        continue-on-error: true
      - run: echo "race detector failed but job is optional"
        if: job.steps.race.status == failure()

  frankenstein:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - run: |
          go mod tidy
        working-directory: e2e/testbuild
      - name: display go.sum diff
        working-directory: e2e/testbuild
        run: |
          git diff --exit-code go.sum && exit 0
          echo "# go.sum diff" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          git diff go.sum >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - run: |
          go run .
        working-directory: e2e/testbuild

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - uses: open-policy-agent/setup-opa@950f159a49aa91f9323f36f1de81c7f6b5de9576 # v2.3.0
        with:
          version: latest
          static: true
      - run: |
          go run main.go test --coverage bundle \
          | opa eval -f raw -I -d build/simplecov/simplecov.rego data.build.simplecov.from_opa \
          > coverage.json
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          fail_ci_if_error: false
          files: ./coverage.json
          name: regal
          token: ${{ secrets.CODECOV_TOKEN }} # required
