name: "Update EOPA caps"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch:
    name: Fetch EOPA caps
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      RQ_VERSION: v0.0.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - name: Restore rq cache
        id: cache-rq
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: go install git.sr.ht/~charles/rq/cmd/rq@${{ env.RQ_VERSION }}
        if: steps.cache-rq.outputs.cache-hit != 'true'
      - name: Cache rq binary
        if: steps.cache-rq.outputs.cache-hit != 'true'
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/go/bin/rq
          key: ${{ runner.os }}-${{ runner.arch }}-go-rq-${{ env.RQ_VERSION }}
      - run: build/do.rq fetch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          title: "automated: update capabilities"
          branch: create-pull-request/caps
          add-paths: |
            internal/capabilities/embedded/eopa/*.json
